GET http://localhost:3000/posts
###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "rtertre0@toplist.cz",
      "pwd": "wN2rQ3g"
}
####

POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "userName":"lcoltart0",
    "email":"cnulty0@scientificamerican.com",
    "userPassword":"dVRMYcx"
}