GET http://localhost:3000/posts
###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "elanegran0@wikia.com",
      "pwd": "5ai4kZSqquKs"
}
####

POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "userName":"lcoltart0ry",
    "email":"cnurrlty0@scientificamerican.com",
    "pwd":"dVRMYcxr"
}